//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_First___Complex_Type
{
    using System;
    
    public partial class ProductAttributes
    {
        public string Size { get; set; }
        public string Color { get; set; }
        public string Style { get; set; }
    }
}
