using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SP_Mapping___Return_Complex_Type
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new AWEntities())
            {
                // Complex Type GetProductCategory_Result auto generated by EF
                GetProductCategory_Result details = context.GetProductCategory(1).FirstOrDefault();
                Console.WriteLine(details.Name);
            }

            Console.WriteLine("Press [Enter] to exit...");
            Console.ReadLine();
        }
    }
}
